name: Test and Publish PowerShell Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Test-ModuleManifest
        run: |
          Test-ModuleManifest -Path .\src\UtilityTools\Clear-Temporary\Clear-Temporary.psd1
          Test-ModuleManifest -Path .\src\PlcTools\Format-TextByRegex\Format-TextByRegex.psd1
        shell: pwsh

      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\src\*.psm1 -Setting ".\src\ScriptAnalyzerProfile.txt" -Recurse -Outvariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }

  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path /src/PlcTools/Format-TextByRegex -NuGetApiKey $env:NUGET_KEY -WhatIf -Verbose
          Publish-Module -Path /src/PlcTools/Clear-Temporary -NuGetApiKey $env:NUGET_KEY -WhatIf -Verbose
