name: Testar e Publicar Módulos PowerShell

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testar-e-publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Testar todos os manifestos
        shell: pwsh
        run: |
          $manifests = Get-ChildItem -Path ./src -Include *.psd1 -Recurse
          Write-Output "Encontrados $($manifests.Count) manifestos para teste."
          foreach ($m in $manifests) {
            Write-Output "Testando: $($m.FullName)"
            Test-ModuleManifest -Path $m.FullName -ErrorAction Stop
          }

      - name: Instalar PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop

      - name: Analisar código com ScriptAnalyzer
        shell: pwsh
        run: |
          $issues = Invoke-ScriptAnalyzer -Path ./src/**/*.psm1 -Setting ./src/ScriptAnalyzerProfile.txt -Recurse
          $errors = $issues | Where-Object Severity -eq 'Error'
          $warnings = $issues | Where-Object Severity -eq 'Warning'

          if ($errors) {
            Write-Error "$($errors.Count) erros encontrados. $($warnings.Count) avisos."
            exit 1
          } else {
            Write-Output "Sem erros. $($warnings.Count) avisos encontrados."
          }

      - name: Verificar versão e publicar módulos (dinâmico)
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          $manifests = Get-ChildItem -Path ./src -Include *.psd1 -Recurse

          foreach ($manifestFile in $manifests) {
            try {
              Write-Output "Verificando módulo: $($manifestFile.FullName)"

              $manifest = Import-PowerShellDataFile -Path $manifestFile.FullName
              $moduleName = $manifest.RootModule -replace '\.psm1$', ''
              $moduleVersion = $manifest.ModuleVersion
              $modulePath = $manifestFile.DirectoryName

              Write-Output "Módulo: $moduleName | Versão: $moduleVersion"

              $url = "https://www.powershellgallery.com/api/v2/FindPackagesById()?id='$moduleName'"
              $response = Invoke-RestMethod -Uri $url -ErrorAction Stop

              $existingVersions = $response.properties.version
              write-Output "$response.properties.version encontrados"

              if ($existingVersions -contains $moduleVersion) {
                Write-Output "$moduleName versão $moduleVersion já publicada. Ignorando..."
                continue
              }

              Write-Output "Publicando $moduleName versão $moduleVersion..."
              Publish-Module -Path $modulePath -NuGetApiKey $env:NUGET_KEY -Verbose

            } catch {
              Write-Error "Erro ao processar módulo $($manifestFile.FullName): $_"
              continue
            }
          }
