name: Test and Publish PowerShell Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test all Module Manifests
        shell: pwsh
        run: |
          Get-ChildItem -Path .\src\**\*.psd1 | ForEach-Object {
              Write-Output "Testing manifest: $($_.FullName)"
              Test-ModuleManifest -Path $_.FullName
          }

      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop

      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\src\**\*.psm1 -Setting ".\src\ScriptAnalyzerProfile.txt" -Recurse -OutVariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }

      - name: Build and publish (dry-run)
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Get-ChildItem -Path .\src\* -Directory | ForEach-Object {
              Write-Output "Publishing module: $($_.FullName)"
              Publish-Module -Path $_.FullName -NuGetApiKey $env:NUGET_KEY -WhatIf -Verbose
          }
